/**
 * MLBB Counter Pro - Database Seeder
 * ------------------------------------
 * Seeds the MongoDB database with hero and item data.
 * Can be run as a script or triggered via API.
 *
 * Usage (via API): POST /api/seed
 * Usage (script): npx ts-node --compiler-options '{"module":"commonjs"}' src/lib/seed/seedDatabase.ts
 */

import { connectToDatabase } from "@/lib/db/mongodb";
import Hero from "@/lib/models/Hero";
import Item from "@/lib/models/Item";

/**
 * Default hero data for bootstrapping when scraping hasn't run yet.
 * These are the canonical MLBB heroes with their attributes.
 */
export const DEFAULT_HERO_DATA = [
  {
    heroId: 1,
    name: "Tigreal",
    title: "The Guardian",
    role: "Tank",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "low",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: ["shield"],
    imageUrl: "",
    stats: { hp: 3200, physicalAttack: 100, magicPower: 0, physicalDef: 30, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 2,
    name: "Lancelot",
    title: "The Swift Blade",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "none",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: [],
    imageUrl: "",
    stats: { hp: 2200, physicalAttack: 200, magicPower: 0, physicalDef: 15, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 3,
    name: "Minotaur",
    title: "The Raging Bull",
    role: "Tank",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "low",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: ["heal", "shield"],
    imageUrl: "",
    stats: { hp: 3400, physicalAttack: 110, magicPower: 0, physicalDef: 25, magicDef: 20 },
    skills: [],
  },
  {
    heroId: 4,
    name: "Lesley",
    title: "The Sniper",
    role: "Marksman",
    damageType: "physical",
    playStyle: "poke",
    mobility: "medium",
    crowdControl: "none",
    range: "ranged",
    survivability: "low",
    powerSpike: "late",
    tags: ["stealth"],
    imageUrl: "",
    stats: { hp: 2100, physicalAttack: 180, magicPower: 0, physicalDef: 12, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 5,
    name: "Gusion",
    title: "The Dagger Master",
    role: "Assassin",
    damageType: "magic",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "soft",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: [],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 0, magicPower: 250, physicalDef: 14, magicDef: 12 },
    skills: [],
  },
  {
    heroId: 6,
    name: "Chang'e",
    title: "The Moon Priestess",
    role: "Mage",
    damageType: "magic",
    playStyle: "poke",
    mobility: "low",
    crowdControl: "soft",
    range: "ranged",
    survivability: "low",
    powerSpike: "mid",
    tags: ["shield"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 0, magicPower: 220, physicalDef: 10, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 7,
    name: "Franco",
    title: "The Hook Master",
    role: "Tank",
    damageType: "physical",
    playStyle: "burst",
    mobility: "low",
    crowdControl: "hard",
    range: "melee",
    survivability: "medium",
    powerSpike: "mid",
    tags: [],
    imageUrl: "",
    stats: { hp: 3000, physicalAttack: 120, magicPower: 0, physicalDef: 28, magicDef: 18 },
    skills: [],
  },
  {
    heroId: 8,
    name: "Miya",
    title: "The Moonlight Archer",
    role: "Marksman",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "medium",
    crowdControl: "none",
    range: "ranged",
    survivability: "low",
    powerSpike: "late",
    tags: [],
    imageUrl: "",
    stats: { hp: 2200, physicalAttack: 170, magicPower: 0, physicalDef: 13, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 9,
    name: "Helcurt",
    title: "The Silent Shadow",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "soft",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: ["stealth"],
    imageUrl: "",
    stats: { hp: 2400, physicalAttack: 190, magicPower: 0, physicalDef: 16, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 10,
    name: "Natalia",
    title: "The Assassin",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "soft",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: ["stealth"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 210, magicPower: 0, physicalDef: 15, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 11,
    name: "Valentina",
    title: "The Heiress",
    role: "Mage",
    damageType: "magic",
    playStyle: "burst",
    mobility: "medium",
    crowdControl: "soft",
    range: "ranged",
    survivability: "medium",
    powerSpike: "mid",
    tags: [],
    imageUrl: "",
    stats: { hp: 2400, physicalAttack: 0, magicPower: 240, physicalDef: 12, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 12,
    name: "Grock",
    title: "The Guardian",
    role: "Tank",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "low",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: ["shield"],
    imageUrl: "",
    stats: { hp: 3300, physicalAttack: 105, magicPower: 0, physicalDef: 32, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 13,
    name: "Chou",
    title: "The Dragon Boy",
    role: "Fighter",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "hard",
    range: "melee",
    survivability: "medium",
    powerSpike: "early",
    tags: [],
    imageUrl: "",
    stats: { hp: 2600, physicalAttack: 160, magicPower: 0, physicalDef: 20, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 14,
    name: "Ruby",
    title: "The Scythe Bearer",
    role: "Fighter",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "medium",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: ["lifesteal", "anti_heal"],
    imageUrl: "",
    stats: { hp: 2700, physicalAttack: 140, magicPower: 0, physicalDef: 22, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 15,
    name: "Eudora",
    title: "The Lightning Weaver",
    role: "Mage",
    damageType: "magic",
    playStyle: "burst",
    mobility: "low",
    crowdControl: "hard",
    range: "ranged",
    survivability: "low",
    powerSpike: "mid",
    tags: [],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 0, magicPower: 260, physicalDef: 10, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 16,
    name: "Khufra",
    title: "The Desert Tyrant",
    role: "Tank",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "medium",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: ["anti_heal"],
    imageUrl: "",
    stats: { hp: 3100, physicalAttack: 100, magicPower: 0, physicalDef: 26, magicDef: 20 },
    skills: [],
  },
  {
    heroId: 17,
    name: "Kagura",
    title: "The Shrine Maiden",
    role: "Mage",
    damageType: "magic",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "hard",
    range: "ranged",
    survivability: "medium",
    powerSpike: "mid",
    tags: [],
    imageUrl: "",
    stats: { hp: 2400, physicalAttack: 0, magicPower: 250, physicalDef: 12, magicDef: 18 },
    skills: [],
  },
  {
    heroId: 18,
    name: "Belerick",
    title: "The Verdant Guardian",
    role: "Tank",
    damageType: "magic",
    playStyle: "sustain",
    mobility: "low",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "late",
    tags: ["shield", "anti_heal"],
    imageUrl: "",
    stats: { hp: 3400, physicalAttack: 0, magicPower: 100, physicalDef: 28, magicDef: 22 },
    skills: [],
  },
  {
    heroId: 19,
    name: "Lunox",
    title: "The Twins of Chaos",
    role: "Mage",
    damageType: "mixed",
    playStyle: "burst",
    mobility: "medium",
    crowdControl: "none",
    range: "ranged",
    survivability: "medium",
    powerSpike: "late",
    tags: ["true_damage"],
    imageUrl: "",
    stats: { hp: 2400, physicalAttack: 0, magicPower: 260, physicalDef: 12, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 20,
    name: "Claude",
    title: "The Gunslinger",
    role: "Marksman",
    damageType: "physical",
    playStyle: "poke",
    mobility: "high",
    crowdControl: "none",
    range: "ranged",
    survivability: "low",
    powerSpike: "late",
    tags: ["summon"],
    imageUrl: "",
    stats: { hp: 2200, physicalAttack: 180, magicPower: 0, physicalDef: 12, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 21,
    name: "Karrie",
    title: "The Void Chaser",
    role: "Marksman",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "medium",
    crowdControl: "none",
    range: "ranged",
    survivability: "low",
    powerSpike: "late",
    tags: ["true_damage"],
    imageUrl: "",
    stats: { hp: 2200, physicalAttack: 175, magicPower: 0, physicalDef: 13, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 22,
    name: "Akai",
    title: "The Great Panda",
    role: "Tank",
    damageType: "physical",
    playStyle: "sustain",
    mobility: "medium",
    crowdControl: "hard",
    range: "melee",
    survivability: "high",
    powerSpike: "mid",
    tags: [],
    imageUrl: "",
    stats: { hp: 3200, physicalAttack: 100, magicPower: 0, physicalDef: 30, magicDef: 18 },
    skills: [],
  },
  {
    heroId: 23,
    name: "Estes",
    title: "The Starlight Healer",
    role: "Support",
    damageType: "magic",
    playStyle: "sustain",
    mobility: "low",
    crowdControl: "none",
    range: "ranged",
    survivability: "low",
    powerSpike: "mid",
    tags: ["heal"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 0, magicPower: 180, physicalDef: 10, magicDef: 14 },
    skills: [],
  },
  {
    heroId: 24,
    name: "Angela",
    title: "The Heart of the Pack",
    role: "Support",
    damageType: "magic",
    playStyle: "poke",
    mobility: "low",
    crowdControl: "soft",
    range: "ranged",
    survivability: "low",
    powerSpike: "mid",
    tags: ["heal", "shield"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 0, magicPower: 190, physicalDef: 10, magicDef: 15 },
    skills: [],
  },
  {
    heroId: 25,
    name: "Hayabusa",
    title: "The Shadow of Darkness",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "none",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: ["stealth", "true_damage"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 200, magicPower: 0, physicalDef: 14, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 26,
    name: "Fanny",
    title: "The Blue Butterfly",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "none",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: [],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 210, magicPower: 0, physicalDef: 14, magicDef: 10 },
    skills: [],
  },
  {
    heroId: 27,
    name: "Ling",
    title: "The Wind Rider",
    role: "Assassin",
    damageType: "physical",
    playStyle: "burst",
    mobility: "high",
    crowdControl: "none",
    range: "melee",
    survivability: "low",
    powerSpike: "early",
    tags: ["stealth"],
    imageUrl: "",
    stats: { hp: 2300, physicalAttack: 200, magicPower: 0, physicalDef: 15, magicDef: 10 },
    skills: [],
  },
];

export const DEFAULT_ITEM_DATA = [
  {
    itemId: 1,
    name: "Antique Cuirass",
    type: "defense",
    cost: 2170,
    stats: { physicalDef: 70, magicDef: 0, hp: 0, regen: 0 },
    passive: "Reduces enemy physical attack by 8% per stack (max 3).",
    tags: ["physical_def", "anti_burst"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 2,
    name: "Blade Armor",
    type: "defense",
    cost: 1960,
    stats: { physicalDef: 90, magicDef: 0, hp: 0, regen: 0 },
    passive: "Reflects 25% of basic attack damage taken as magic damage.",
    tags: ["physical_def", "anti_auto"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 3,
    name: "Athena's Shield",
    type: "defense",
    cost: 2150,
    stats: { physicalDef: 0, magicDef: 62, hp: 0, regen: 0 },
    passive: "Gain a shield that blocks 50% of incoming magic damage.",
    tags: ["magic_def", "anti_burst"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 4,
    name: "Radiant Armor",
    type: "defense",
    cost: 1880,
    stats: { physicalDef: 0, magicDef: 48, hp: 1200, regen: 20 },
    passive: "Reduces magic damage taken by 2-10 per stack.",
    tags: ["magic_def", "anti_sustain"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 5,
    name: "Twilight Armor",
    type: "defense",
    cost: 2200,
    stats: { physicalDef: 20, magicDef: 20, hp: 1500, regen: 0 },
    passive: "Blocks damage exceeding 600 from a single hit.",
    tags: ["hp", "anti_burst", "anti_crit"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 6,
    name: "Dominance Ice",
    type: "defense",
    cost: 2010,
    stats: { physicalDef: 70, magicDef: 0, hp: 0, regen: 0 },
    passive: "Reduces enemy attack speed and shield/heal effect by 50%.",
    tags: ["physical_def", "anti_heal", "anti_attack_speed"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 7,
    name: "Necklace of Durance",
    type: "magic",
    cost: 2050,
    stats: { physicalDef: 0, magicDef: 0, hp: 0, regen: 0 },
    passive: "Reduces enemy healing and shield by 50% for 3s.",
    tags: ["anti_heal"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 8,
    name: "Sea Halberd",
    type: "attack",
    cost: 1950,
    stats: { physicalDef: 0, magicDef: 0, hp: 0, regen: 0 },
    passive: "Reduces enemy healing and shield by 50% for 3s.",
    tags: ["anti_heal", "physical_attack"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 9,
    name: "Cursed Helmet",
    type: "defense",
    cost: 1860,
    stats: { physicalDef: 0, magicDef: 24, hp: 1200, regen: 0 },
    passive: "Deals magic damage equal to 4% of max HP to nearby enemies.",
    tags: ["magic_def", "hp", "aoe_magic"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 10,
    name: "Immortality",
    type: "defense",
    cost: 2200,
    stats: { physicalDef: 0, magicDef: 0, hp: 0, regen: 0 },
    passive: "Resurrects with 15% HP after 2.5s.",
    tags: ["survival", "anti_burst"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 11,
    name: "Tough Boots",
    type: "boots",
    cost: 720,
    stats: { physicalDef: 0, magicDef: 22, hp: 0, regen: 0 },
    passive: "Reduces CC duration by 30%.",
    tags: ["magic_def", "cc_reduction"],
    imageUrl: "",
    counters: [],
  },
  {
    itemId: 12,
    name: "Warrior Boots",
    type: "boots",
    cost: 720,
    stats: { physicalDef: 22, magicDef: 0, hp: 0, regen: 0 },
    passive: "Increases physical defense.",
    tags: ["physical_def"],
    imageUrl: "",
    counters: [],
  },
];

export async function seedDatabase() {
  console.log("🌱 Seeding database...");

  await connectToDatabase();

  // Seed heroes
  const existingHeroes = await Hero.countDocuments();
  if (existingHeroes === 0) {
    await Hero.insertMany(DEFAULT_HERO_DATA);
    console.log(`✅ Seeded ${DEFAULT_HERO_DATA.length} heroes`);
  } else {
    console.log(`⏭️ Heroes collection already has ${existingHeroes} documents, skipping...`);
  }

  // Seed items
  const existingItems = await Item.countDocuments();
  if (existingItems === 0) {
    await Item.insertMany(DEFAULT_ITEM_DATA);
    console.log(`✅ Seeded ${DEFAULT_ITEM_DATA.length} items`);
  } else {
    console.log(`⏭️ Items collection already has ${existingItems} documents, skipping...`);
  }

  console.log("🌱 Database seeding complete!");
  return {
    seededHeroes: existingHeroes === 0 ? DEFAULT_HERO_DATA.length : 0,
    seededItems: existingItems === 0 ? DEFAULT_ITEM_DATA.length : 0,
  };
}

// Run directly if called as script
if (require.main === module) {
  seedDatabase()
    .then((result) => {
      console.log("Seed result:", result);
      process.exit(0);
    })
    .catch((err) => {
      console.error("Seed failed:", err);
      process.exit(1);
    });
}