name: Deprecated Action

on:
  workflow_dispatch:

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: echo "This action is deprecated. Use daily-sync.yml instead."
